DROP TABLE IF EXISTS EMAIL
GO

CREATE TABLE EMAIL (
	ID_EMAIL INT NOT NULL IDENTITY,
	SENDER VARCHAR(200) DEFAULT NULL,
	RECIPIENT VARCHAR(200) DEFAULT NULL,
	BODY VARCHAR(MAX) DEFAULT NULL,
	SEND_STATUS VARCHAR(200) DEFAULT NULL,
	CONSTRAINT PK_EMAIL PRIMARY KEY (ID_EMAIL)
)
GO
