DROP TABLE IF EXISTS EMAIL
GO

CREATE TABLE EMAIL (
	IdEmail INT NOT NULL IDENTITY,
	Sender VARCHAR(200) DEFAULT NULL,
	Recipient VARCHAR(200) DEFAULT NULL,
	Body VARCHAR(MAX) DEFAULT NULL,
	SendStatus VARCHAR(200) DEFAULT NULL,
	CONSTRAINT PK_EMAIL PRIMARY KEY (IdEmail)
)
GO
